env:
  contexts:
    - name: Default Context
      urls:
        - https://juice-shop.herokuapp.com

jobs:
  - type: spider
    name: Spider the target
    parameters:
      context: Default Context
      maxDuration: 5

  - type: passiveScan-config
    name: Passive Scan Settings

  - type: outputSummary
    parameters:
      summaryFile: /zap/wrk/summary.json

  - type: report
    parameters:
      template: traditional-html
      reportDir: /zap/wrk
      reportFile: zap_report.html
