name: ZAP Scan and Gemini Mitigation

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: "Website to scan"
        required: true

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run ZAP scan using GHCR image
        run: |
          docker run -v ${{ github.workspace }}:/zap/wrk \
          ghcr.io/zaproxy/zaproxy:stable zap.sh \
          -cmd -quickurl "https://example.com" \
          -quickout /zap/wrk/zap_report.xml


      - name: Commit ZAP report to branch
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git checkout -b zap-report
            git add zap_report.xml
            git commit -m "Add ZAP scan report"
            git push -f origin zap-report
          

