name: ZAP Scan and Gemini Mitigation

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: "Website to scan"
        required: true

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create directory for ZAP reports
        run: mkdir -p ${{ github.workspace }}/zap-output

      - name: Run ZAP 5-minute baseline scan
        run: |
          docker run --network="host" \
            -v ${{ github.workspace }}/zap-output:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
              -t "${{ github.event.inputs.target_url }}" \
              -r /zap/wrk/zap_report.html \
              -x /zap/wrk/zap_report.xml \
              -m 5

      - name: Verify ZAP report exists
        run: |
          if [ -f "${{ github.workspace }}/zap-output/zap_report.xml" ]; then
            echo "✅ Report generated successfully."
          else
            echo "❌ Report was not generated."
            exit 1
          fi

      - name: Commit ZAP report to branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git checkout -b zap-report || git checkout zap-report
          cp ${{ github.workspace }}/zap-output/zap_report.* .
          git add zap_report.*
          git commit -m "Add ZAP scan report (5-minute baseline)"
          git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git zap-report
