name: ZAP Full Scan and Report

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: "Website to scan"
        required: true

jobs:
  zap-full-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create a directory for the ZAP report
        run: mkdir -p ${{ github.workspace }}/zap-output

      - name: Run full ZAP scan
        run: |
          docker run --network="host" \
            -v ${{ github.workspace }}/zap-output:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-full-scan.py \
              -t "${{ github.event.inputs.target_url }}" \
              -r full_zap_report.html \
              -x full_zap_report.xml \
              -I  # Ignore exit code on alerts to prevent build failure

      - name: Check ZAP report exists
        run: |
          if [ -f "${{ github.workspace }}/zap-output/full_zap_report.xml" ]; then
            echo "✅ ZAP full scan completed."
          else
            echo "❌ ZAP scan report not found."
            exit 1
          fi

      - name: Commit ZAP report to branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b zap-report || git checkout zap-report
          cp ${{ github.workspace }}/zap-output/full_zap_report.xml .
          cp ${{ github.workspace }}/zap-output/full_zap_report.html .
          git add full_zap_report.*
          git commit -m "Add ZAP full scan report"
          git push -f origin zap-report
