name: ZAP Scan and Gemini Mitigation

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: "Website to scan"
        required: true

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create a directory for the ZAP report
        run: mkdir -p ${{ github.workspace }}/zap-output

      - name: Check directory permissions
        run: ls -ld ${{ github.workspace }}/zap-output

      - name: Run ZAP scan using GHCR image with correct user permissions
        run: |
          docker run \
            --user $(id -u):$(id -g) \
            -v ${{ github.workspace }}/zap-output:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable sh -c "zap.sh \
            -cmd -quickurl '${{ github.event.inputs.target_url }}' \
            -quickout /zap/wrk/zap_report.xml"

      - name: Verify ZAP report exists
        run: |
          if [ -f "${{ github.workspace }}/zap-output/zap_report.xml" ]; then
            echo "✅ Report generated"
          else
            echo "❌ Report was not generated"
            exit 1
          fi

      - name: Commit ZAP report to branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b zap-report || git checkout zap-report
          cp ${{ github.workspace }}/zap-output/zap_report.xml .
          git add ./zap_report.xml
          git commit -m "Add ZAP scan report"
          git push -f origin zap-report
