name: ZAP Scan and Gemini Mitigation

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: "Website to scan"
        required: true

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ZAP output directory
        run: mkdir -p zap-output

      - name: Run ZAP Docker container and generate report
        run: |
          docker run --user root \
            -v ${{ github.workspace }}/zap-output:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable \
            zap.sh -cmd -quickurl "${{ github.event.inputs.target_url }}" \
            -quickout /zap/wrk/zap_report.xml

      - name: Verify ZAP report exists
        run: |
          if [ -f "zap-output/zap_report.xml" ]; then
            echo "✅ Report generated successfully."
          else
            echo "❌ Report not found!"
            exit 1
          fi

      - name: Commit report to `zap-report` branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin zap-report || true
          git checkout zap-report || git checkout -b zap-report
          cp zap-output/zap_report.xml .
          git add zap_report.xml
          git commit -m "Add latest ZAP scan report"
          git push -f origin zap-report
