name: ZAP Security Scan

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create writable output directory
      run: mkdir -p zap_output

    - name: Copy zap.yaml into output directory
      run: cp zap.yaml zap_output/zap.yaml

    - name: Run ZAP Scan with Automation Framework
      uses: docker://ghcr.io/zaproxy/zaproxy:stable
      with:
        entrypoint: ""
      args: >
        zap.sh -cmd -autorun /zap/wrk/zap.yaml
      volume: ${{ github.workspace }}/zap_output:/zap/wrk

    - name: Upload ZAP HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: zap-scan-report
        path: zap_output/zap_report.html
